fix bug when use pycharm remote
TkAgee cannot be imported when using pycharm remote.

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running